RuntimeError: Input tensors need to be on the same GPU, but found the following tensor and device combinations:  [(torch.Size([1, 19660800]), device(type='cuda', index=1)), (torch.Size([614400]), device(type='cuda', index=0)), (torch.Size([7680, 5120]), device(type='cuda', index=1))]